In [1]:
import numpy as np                # Apertar Shift + Tab para mostrar o uso de tal método

In [2]:
lista = [1, 2, 3]                 # Lista vetorial

### np.array

In [3]:
np.array(lista)                   # Tranforma a lista em array do numpy

array([1, 2, 3])

In [4]:
np.arange(0, 50)                  # Mesmo que range, só que como array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [5]:
np.array(range(0, 50))            # Mesma coisa, mas diferente

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

### np.zeros - np.ones

In [6]:
np.zeros(5)                       # Array com zeros

array([0., 0., 0., 0., 0.])

In [7]:
np.zeros((5, 5))                  # Matriz bidimensional com zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Se quiser uma matriz tem que mandar em uma tupla como no caso 2 dimensões a tupla (5, 5)

In [8]:
np.ones((3, 3))                   # Mesmo que zeros mas com 1's

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.eye(4)                         # Matriz idêntidade

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### np.linspace
    np.linspace(
        start -> Começo
        stop  -> Fim
        num   -> Quantos elementos na lista igualmente espaçados
    )

In [10]:
np.linspace(50, 90, 41)

array([50., 51., 52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62.,
       63., 64., 65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75.,
       76., 77., 78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88.,
       89., 90.])

In [11]:
np.linspace(5, 20, 4)

array([ 5., 10., 15., 20.])

### np.random

In [12]:
np.random.rand(5)                 # Cria 5 número de 0 a 1 com uma distribuição uniformeou 
                                  # ou seja, todos os números tem a mesma probabiliade de serem escolhidos

array([0.07943227, 0.1117057 , 0.09749393, 0.4092738 , 0.33437213])

In [13]:
np.random.rand(5) * 100           # O mesmo só que de 0 a 100

array([98.00683938, 50.44878931, 60.83661082, 72.68801871, 86.98101033])

In [14]:
np.random.rand(5, 4)              # Nesse caso em matrizes, não precisa ser uma tupla

array([[0.19993241, 0.19331285, 0.88076772, 0.67173078],
       [0.16522994, 0.06847066, 0.55062109, 0.19430688],
       [0.74038426, 0.59130382, 0.02617135, 0.28018935],
       [0.89218058, 0.4690431 , 0.78190986, 0.29482225],
       [0.32970431, 0.09341903, 0.65771644, 0.10079914]])

In [15]:
np.random.randn(5)                # O mesmo, só que com uma distribuição gaussiana

array([-0.49321401, -0.47048018, -0.3246903 ,  0.41709827,  0.82775799])

In [16]:
np.random.randint(0, 10, 10)      # Cria 10 números (3º parâmetro) inteiros de 0 a 10

array([9, 7, 9, 0, 4, 9, 9, 4, 6, 7])

In [17]:
np.round(np.random.rand(10) * 10, 0)   # Mesmo que randint, mas com o método rand

array([3., 6., 7., 2., 2., 8., 3., 3., 6., 6.])

### np.reshape

In [18]:
arr = np.random.rand(25)
arr

array([0.95511576, 0.28334214, 0.9357033 , 0.73613546, 0.53556671,
       0.75057043, 0.26795453, 0.32529272, 0.5914901 , 0.62313483,
       0.5012171 , 0.14635851, 0.99042831, 0.45045132, 0.81178704,
       0.47720627, 0.11948636, 0.67367205, 0.80820542, 0.80087439,
       0.91611167, 0.98450082, 0.32821505, 0.68831503, 0.87037805])

In [19]:
arr = arr.reshape((5, 5))          # Precisa ser tupla e o produto deles tem que ser o tamanho do array
                                   # Nesse caso 5 x 5 = 25
arr

array([[0.95511576, 0.28334214, 0.9357033 , 0.73613546, 0.53556671],
       [0.75057043, 0.26795453, 0.32529272, 0.5914901 , 0.62313483],
       [0.5012171 , 0.14635851, 0.99042831, 0.45045132, 0.81178704],
       [0.47720627, 0.11948636, 0.67367205, 0.80820542, 0.80087439],
       [0.91611167, 0.98450082, 0.32821505, 0.68831503, 0.87037805]])

In [20]:
arr.shape                          # Isso é o shape, o tamanho do array

(5, 5)

In [21]:
arr.max()                          # Retorna o valor máximo do array

0.9904283107494124

In [22]:
arr.min()                          # Retorna o valor mínimodo array

0.11948636492442477

In [23]:
arr.argmax()                       # Retorna o índice do maior valor do array

12

In [24]:
arr.argmin()                       # Retorna o índice do menor valor do array

16